version: "3.7"

services:
    parser:
        restart: always
        build: ./parser
        command: "pipenv run python ./run.py"
        expose:
            - ${PARSER_PORT}
        env_file:
            - .env
        volumes:
            - ./parser:/parser
    mongo:
        restart: always
        image: mongo:latest
        volumes:
            - ./etc/data:/data/db
            - ./etc/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        expose:
            - ${MONGO_PORT}
    updater:
        restart: always
        build: ./updater
        command: "pipenv run python ./run.py"
        expose:
            - ${UPDATER_PORT}
        depends_on:
            - mongo
        env_file:
            - .env
        volumes:
            - ./updater:/updater
    api:
        restart: always
        build: ./api
        command: "pipenv run python ./run.py"
        depends_on:
            - mongo
        expose:
          - ${API_PORT}
        env_file:
            - .env
        volumes:
            - ./api:/api
